const fs = require('fs');
const path = require('path');

// Diccionario de países: código ISO -> { idioma: nombre }
const PAISES = {
  "ES": { es:"España", en:"Spain", pt:"Espanha", fr:"Espagne", de:"Spanien", it:"Spagna" },
  "PT": { es:"Portugal", en:"Portugal", pt:"Portugal", fr:"Portugal", de:"Portugal", it:"Portogallo" },
  "FR": { es:"Francia", en:"France", pt:"França", fr:"France", de:"Frankreich", it:"Francia" },
  "GB": { es:"Reino Unido", en:"United Kingdom", pt:"Reino Unido", fr:"Royaume-Uni", de:"Vereinigtes Königreich", it:"Regno Unito" },
  "IE": { es:"Irlanda", en:"Ireland", pt:"Irlanda", fr:"Irlande", de:"Irland", it:"Irlanda" },
  "IT": { es:"Italia", en:"Italy", pt:"Itália", fr:"Italie", de:"Italien", it:"Italia" },
  "DE": { es:"Alemania", en:"Germany", pt:"Alemanha", fr:"Allemagne", de:"Deutschland", it:"Germania" },
  "AT": { es:"Austria", en:"Austria", pt:"Áustria", fr:"Autriche", de:"Österreich", it:"Austria" },
  "BE": { es:"Bélgica", en:"Belgium", pt:"Bélgica", fr:"Belgique", de:"Belgien", it:"Belgio" },
  "NL": { es:"Países Bajos", en:"Netherlands", pt:"Países Baixos", fr:"Pays-Bas", de:"Niederlande", it:"Paesi Bassi" },
  "LU": { es:"Luxemburgo", en:"Luxembourg", pt:"Luxemburgo", fr:"Luxembourg", de:"Luxemburg", it:"Lussemburgo" },
  "CH": { es:"Suiza", en:"Switzerland", pt:"Suíça", fr:"Suisse", de:"Schweiz", it:"Svizzera" },
  "US": { es:"Estados Unidos", en:"United States", pt:"Estados Unidos", fr:"États-Unis", de:"Vereinigte Staaten", it:"Stati Uniti" },
  "CA": { es:"Canadá", en:"Canada", pt:"Canadá", fr:"Canada", de:"Kanada", it:"Canada" },
  "MX": { es:"México", en:"Mexico", pt:"México", fr:"Mexique", de:"Mexiko", it:"Messico" },
  "AR": { es:"Argentina", en:"Argentina", pt:"Argentina", fr:"Argentine", de:"Argentinien", it:"Argentina" },
  "BR": { es:"Brasil", en:"Brazil", pt:"Brasil", fr:"Brésil", de:"Brasilien", it:"Brasile" },
  "CL": { es:"Chile", en:"Chile", pt:"Chile", fr:"Chili", de:"Chile", it:"Cile" },
  "CO": { es:"Colombia", en:"Colombia", pt:"Colômbia", fr:"Colombie", de:"Kolumbien", it:"Colombia" },
  "PE": { es:"Perú", en:"Peru", pt:"Peru", fr:"Pérou", de:"Peru", it:"Perù" },
  "VE": { es:"Venezuela", en:"Venezuela", pt:"Venezuela", fr:"Venezuela", de:"Venezuela", it:"Venezuela" },
  "UY": { es:"Uruguay", en:"Uruguay", pt:"Uruguai", fr:"Uruguay", de:"Uruguay", it:"Uruguay" },
  "EC": { es:"Ecuador", en:"Ecuador", pt:"Equador", fr:"Équateur", de:"Ecuador", it:"Ecuador" },
  "BO": { es:"Bolivia", en:"Bolivia", pt:"Bolívia", fr:"Bolivie", de:"Bolivien", it:"Bolivia" },
  "PY": { es:"Paraguay", en:"Paraguay", pt:"Paraguai", fr:"Paraguay", de:"Paraguay", it:"Paraguay" },
  "CU": { es:"Cuba", en:"Cuba", pt:"Cuba", fr:"Cuba", de:"Kuba", it:"Cuba" },
  "DO": { es:"Rep. Dominicana", en:"Dominican Rep.", pt:"Rep. Dominicana", fr:"Rep. Dominicaine", de:"Dominikanische Rep.", it:"Rep. Dominicana" },
  "PR": { es:"Puerto Rico", en:"Puerto Rico", pt:"Porto Rico", fr:"Porto Rico", de:"Puerto Rico", it:"Porto Rico" },
  "AU": { es:"Australia", en:"Australia", pt:"Austrália", fr:"Australie", de:"Australien", it:"Australia" },
  "NZ": { es:"Nueva Zelanda", en:"New Zealand", pt:"Nova Zelândia", fr:"Nouvelle-Zélande", de:"Neuseeland", it:"Nuova Zelanda" },
  "ZA": { es:"Sudáfrica", en:"South Africa", pt:"África do Sul", fr:"Afrique du Sud", de:"Südafrika", it:"Sudafrica" },
  "MA": { es:"Marruecos", en:"Morocco", pt:"Marrocos", fr:"Maroc", de:"Marokko", it:"Marocco" },
  "DZ": { es:"Argelia", en:"Algeria", pt:"Argélia", fr:"Algérie", de:"Algerien", it:"Algeria" },
  "TN": { es:"Túnez", en:"Tunisia", pt:"Tunísia", fr:"Tunisie", de:"Tunesien", it:"Tunisia" },
  "EH": { es:"Sáhara Occidental", en:"Western Sahara", pt:"Saara Ocidental", fr:"Sahara Occidental", de:"Westsahara", it:"Sahara Occidentale" },
  "AD": { es:"Andorra", en:"Andorra", pt:"Andorra", fr:"Andorre", de:"Andorra", it:"Andorra" },
  "GI": { es:"Gibraltar", en:"Gibraltar", pt:"Gibraltar", fr:"Gibraltar", de:"Gibraltar", it:"Gibilterra" },
  "MC": { es:"Mónaco", en:"Monaco", pt:"Mônaco", fr:"Monaco", de:"Monaco", it:"Monaco" },
  "SM": { es:"San Marino", en:"San Marino", pt:"San Marino", fr:"Saint-Marin", de:"San Marino", it:"San Marino" },
  "VA": { es:"Vaticano", en:"Vatican", pt:"Vaticano", fr:"Vatican", de:"Vatikan", it:"Vaticano" },
  "MT": { es:"Malta", en:"Malta", pt:"Malta", fr:"Malte", de:"Malta", it:"Malta" },
  "CY": { es:"Chipre", en:"Cyprus", pt:"Chipre", fr:"Chypre", de:"Zypern", it:"Cipro" },
  "GR": { es:"Grecia", en:"Greece", pt:"Grécia", fr:"Grèce", de:"Griechenland", it:"Grecia" },
  "TR": { es:"Turquía", en:"Turkey", pt:"Turquia", fr:"Turquie", de:"Türkei", it:"Turchia" },
  "RU": { es:"Rusia", en:"Russia", pt:"Rússia", fr:"Russie", de:"Russland", it:"Russia" },
  "UA": { es:"Ucrania", en:"Ukraine", pt:"Ucrânia", fr:"Ukraine", de:"Ukraine", it:"Ucraina" },
  "PL": { es:"Polonia", en:"Poland", pt:"Polônia", fr:"Pologne", de:"Polen", it:"Polonia" },
  "SE": { es:"Suecia", en:"Sweden", pt:"Suécia", fr:"Suède", de:"Schweden", it:"Svezia" },
  "NO": { es:"Noruega", en:"Norway", pt:"Noruega", fr:"Norvège", de:"Norwegen", it:"Norvegia" },
  "FI": { es:"Finlandia", en:"Finland", pt:"Finlândia", fr:"Finlande", de:"Finnland", it:"Finlandia" },
  "DK": { es:"Dinamarca", en:"Denmark", pt:"Dinamarca", fr:"Danemark", de:"Dänemark", it:"Danimarca" },
  "IS": { es:"Islandia", en:"Iceland", pt:"Islândia", fr:"Islande", de:"Island", it:"Islanda" },
  "EE": { es:"Estonia", en:"Estonia", pt:"Estônia", fr:"Estonie", de:"Estland", it:"Estonia" },
  "LV": { es:"Letonia", en:"Latvia", pt:"Letônia", fr:"Lettonie", de:"Lettland", it:"Lettonia" },
  "LT": { es:"Lituania", en:"Lithuania", pt:"Lituânia", fr:"Lituanie", de:"Litauen", it:"Lituania" },
  "CZ": { es:"Chequia", en:"Czechia", pt:"Chéquia", fr:"Tchéquie", de:"Tschechien", it:"Cechia" },
  "SK": { es:"Eslovaquia", en:"Slovakia", pt:"Eslováquia", fr:"Slovaquie", de:"Slowakei", it:"Slovacchia" },
  "HU": { es:"Hungría", en:"Hungary", pt:"Hungria", fr:"Hongrie", de:"Ungarn", it:"Ungheria" },
  "RO": { es:"Rumanía", en:"Romania", pt:"Roménia", fr:"Roumanie", de:"Rumänien", it:"Romania" },
  "BG": { es:"Bulgaria", en:"Bulgaria", pt:"Bulgária", fr:"Bulgarie", de:"Bulgarien", it:"Bulgaria" },
  "RS": { es:"Serbia", en:"Serbia", pt:"Sérvia", fr:"Serbie", de:"Serbien", it:"Serbia" },
  "HR": { es:"Croacia", en:"Croatia", pt:"Croácia", fr:"Croatie", de:"Kroatien", it:"Croazia" },
  "SI": { es:"Eslovenia", en:"Slovenia", pt:"Eslovênia", fr:"Slovénie", de:"Slowenien", it:"Slovenia" },
  "BA": { es:"Bosnia", en:"Bosnia", pt:"Bósnia", fr:"Bosnie", de:"Bosnien", it:"Bosnia" },
  "MK": { es:"Macedonia del Norte", en:"North Macedonia", pt:"Macedônia do Norte", fr:"Macédoine du Nord", de:"Nordmazedonien", it:"Macedonia del Nord" },
  "AL": { es:"Albania", en:"Albania", pt:"Albânia", fr:"Albanie", de:"Albanien", it:"Albania" },
  "ME": { es:"Montenegro", en:"Montenegro", pt:"Montenegro", fr:"Monténégro", de:"Montenegro", it:"Montenegro" },
  "MD": { es:"Moldavia", en:"Moldova", pt:"Moldávia", fr:"Moldavie", de:"Moldau", it:"Moldavia" },
  "BY": { es:"Bielorrusia", en:"Belarus", pt:"Bielorrússia", fr:"Biélorussie", de:"Belarus", it:"Bielorussia" },
  "GE": { es:"Georgia", en:"Georgia", pt:"Geórgia", fr:"Géorgie", de:"Georgien", it:"Georgia" },
  "AM": { es:"Armenia", en:"Armenia", pt:"Armênia", fr:"Arménie", de:"Armenien", it:"Armenia" },
  "AZ": { es:"Azerbaiyán", en:"Azerbaijan", pt:"Azerbaijão", fr:"Azerbaïdjan", de:"Aserbaidschan", it:"Azerbaigian" },
  "KZ": { es:"Kazajistán", en:"Kazakhstan", pt:"Cazaquistão", fr:"Kazakhstan", de:"Kasachstan", it:"Kazakistan" },
  "UZ": { es:"Uzbekistán", en:"Uzbekistan", pt:"Uzbequistão", fr:"Ouzbékistan", de:"Usbekistan", it:"Uzbekistan" },
  "CN": { es:"China", en:"China", pt:"China", fr:"Chine", de:"China", it:"Cina" },
  "JP": { es:"Japón", en:"Japan", pt:"Japão", fr:"Japon", de:"Japan", it:"Giappone" },
  "KR": { es:"Corea del Sur", en:"South Korea", pt:"Coreia do Sul", fr:"Corée du Sud", de:"Südkorea", it:"Corea del Sud" },
  "KP": { es:"Corea del Norte", en:"North Korea", pt:"Coreia do Norte", fr:"Corée du Nord", de:"Nordkorea", it:"Corea del Nord" },
  "IN": { es:"India", en:"India", pt:"Índia", fr:"Inde", de:"Indien", it:"India" },
  "PK": { es:"Paquistán", en:"Pakistan", pt:"Paquistão", fr:"Pakistan", de:"Pakistan", it:"Pakistan" },
  "BD": { es:"Bangladés", en:"Bangladesh", pt:"Bangladesh", fr:"Bangladesh", de:"Bangladesch", it:"Bangladesh" },
  "LK": { es:"Sri Lanka", en:"Sri Lanka", pt:"Sri Lanka", fr:"Sri Lanka", de:"Sri Lanka", it:"Sri Lanka" },
  "NP": { es:"Nepal", en:"Nepal", pt:"Nepal", fr:"Népal", de:"Nepal", it:"Nepal" },
  "BT": { es:"Bután", en:"Bhutan", pt:"Butão", fr:"Bhoutan", de:"Bhutan", it:"Bhutan" },
  "MM": { es:"Myanmar", en:"Myanmar", pt:"Mianmar", fr:"Myanmar", de:"Myanmar", it:"Myanmar" },
  "TH": { es:"Tailandia", en:"Thailand", pt:"Tailândia", fr:"Thaïlande", de:"Thailand", it:"Thailandia" },
  "LA": { es:"Laos", en:"Laos", pt:"Laos", fr:"Laos", de:"Laos", it:"Laos" },
  "KH": { es:"Camboya", en:"Cambodia", pt:"Camboja", fr:"Cambodge", de:"Kambodscha", it:"Cambogia" },
  "VN": { es:"Vietnam", en:"Vietnam", pt:"Vietnã", fr:"Vietnam", de:"Vietnam", it:"Vietnam" },
  "MY": { es:"Malasia", en:"Malaysia", pt:"Malásia", fr:"Malaisie", de:"Malaysia", it:"Malesia" },
  "SG": { es:"Singapur", en:"Singapore", pt:"Singapura", fr:"Singapour", de:"Singapur", it:"Singapore" },
  "ID": { es:"Indonesia", en:"Indonesia", pt:"Indonésia", fr:"Indonésie", de:"Indonesien", it:"Indonesia" },
  "PH": { es:"Filipinas", en:"Philippines", pt:"Filipinas", fr:"Philippines", de:"Philippinen", it:"Filippine" },
  "BN": { es:"Brunéi", en:"Brunei", pt:"Brunei", fr:"Brunei", de:"Brunei", it:"Brunei" },
  "TL": { es:"Timor Oriental", en:"East Timor", pt:"Timor-Leste", fr:"Timor oriental", de:"Osttimor", it:"Timor Est" },
  "MN": { es:"Mongolia", en:"Mongolia", pt:"Mongólia", fr:"Mongolie", de:"Mongolei", it:"Mongolia" },
  "TW": { es:"Taiwán", en:"Taiwan", pt:"Taiwan", fr:"Taiwan", de:"Taiwan", it:"Taiwan" },
  "HK": { es:"Hong Kong", en:"Hong Kong", pt:"Hong Kong", fr:"Hong Kong", de:"Hongkong", it:"Hong Kong" },
  "MO": { es:"Macao", en:"Macao", pt:"Macau", fr:"Macao", de:"Macao", it:"Macao" },
  "AF": { es:"Afganistán", en:"Afghanistan", pt:"Afeganistão", fr:"Afghanistan", de:"Afghanistan", it:"Afghanistan" },
  "IR": { es:"Irán", en:"Iran", pt:"Irã", fr:"Iran", de:"Iran", it:"Iran" },
  "IQ": { es:"Irak", en:"Iraq", pt:"Iraque", fr:"Irak", de:"Irak", it:"Iraq" },
  "SY": { es:"Siria", en:"Syria", pt:"Síria", fr:"Syrie", de:"Syrien", it:"Siria" },
  "LB": { es:"Líbano", en:"Lebanon", pt:"Líbano", fr:"Liban", de:"Libanon", it:"Libano" },
  "JO": { es:"Jordania", en:"Jordan", pt:"Jordânia", fr:"Jordanie", de:"Jordanien", it:"Giordania" },
  "IL": { es:"Israel", en:"Israel", pt:"Israel", fr:"Israël", de:"Israel", it:"Israele" },
  "PS": { es:"Palestina", en:"Palestine", pt:"Palestina", fr:"Palestine", de:"Palästina", it:"Palestina" },
  "SA": { es:"Arabia Saudí", en:"Saudi Arabia", pt:"Arábia Saudita", fr:"Arabie saoudite", de:"Saudi-Arabien", it:"Arabia Saudita" },
  "AE": { es:"Emiratos Árabes", en:"UAE", pt:"Emirados Árabes", fr:"Émirats arabes unis", de:"VAE", it:"Emirati Arabi Uniti" },
  "QA": { es:"Catar", en:"Qatar", pt:"Catar", fr:"Qatar", de:"Katar", it:"Qatar" },
  "BH": { es:"Baréin", en:"Bahrain", pt:"Bahrein", fr:"Bahreïn", de:"Bahrain", it:"Bahrein" },
  "KW": { es:"Kuwait", en:"Kuwait", pt:"Kuwait", fr:"Koweït", de:"Kuwait", it:"Kuwait" },
  "OM": { es:"Omán", en:"Oman", pt:"Omã", fr:"Oman", de:"Oman", it:"Oman" },
  "YE": { es:"Yemen", en:"Yemen", pt:"Iêmen", fr:"Yémen", de:"Jemen", it:"Yemen" },
  "EG": { es:"Egipto", en:"Egypt", pt:"Egito", fr:"Égypte", de:"Ägypten", it:"Egitto" },
  "LY": { es:"Libia", en:"Libya", pt:"Líbia", fr:"Libye", de:"Libyen", it:"Libia" },
  "SD": { es:"Sudán", en:"Sudan", pt:"Sudão", fr:"Soudan", de:"Sudan", it:"Sudan" },
  "SS": { es:"Sudán del Sur", en:"South Sudan", pt:"Sudão do Sul", fr:"Soudan du Sud", de:"Südsudan", it:"Sudan del Sud" },
  "ET": { es:"Etiopía", en:"Ethiopia", pt:"Etiópia", fr:"Éthiopie", de:"Äthiopien", it:"Etiopia" },
  "ER": { es:"Eritrea", en:"Eritrea", pt:"Eritreia", fr:"Érythrée", de:"Eritrea", it:"Eritrea" },
  "DJ": { es:"Yibuti", en:"Djibouti", pt:"Djibuti", fr:"Djibouti", de:"Dschibuti", it:"Gibuti" },
  "SO": { es:"Somalia", en:"Somalia", pt:"Somália", fr:"Somalie", de:"Somalia", it:"Somalia" },
  "KE": { es:"Kenia", en:"Kenya", pt:"Quênia", fr:"Kenya", de:"Kenia", it:"Kenya" },
  "UG": { es:"Uganda", en:"Uganda", pt:"Uganda", fr:"Ouganda", de:"Uganda", it:"Uganda" },
  "TZ": { es:"Tanzania", en:"Tanzania", pt:"Tanzânia", fr:"Tanzanie", de:"Tansania", it:"Tanzania" },
  "RW": { es:"Ruanda", en:"Rwanda", pt:"Ruanda", fr:"Rwanda", de:"Ruanda", it:"Ruanda" },
  "BI": { es:"Burundi", en:"Burundi", pt:"Burundi", fr:"Burundi", de:"Burundi", it:"Burundi" },
  "MZ": { es:"Mozambique", en:"Mozambique", pt:"Moçambique", fr:"Mozambique", de:"Mosambik", it:"Mozambico" },
  "ZM": { es:"Zambia", en:"Zambia", pt:"Zâmbia", fr:"Zambie", de:"Sambia", it:"Zambia" },
  "ZW": { es:"Zimbabue", en:"Zimbabwe", pt:"Zimbábue", fr:"Zimbabwe", de:"Simbabwe", it:"Zimbabwe" },
  "BW": { es:"Botsuana", en:"Botswana", pt:"Botsuana", fr:"Botswana", de:"Botsuana", it:"Botswana" },
  "NA": { es:"Namibia", en:"Namibia", pt:"Namíbia", fr:"Namibie", de:"Namibia", it:"Namibia" },
  "AO": { es:"Angola", en:"Angola", pt:"Angola", fr:"Angola", de:"Angola", it:"Angola" },
  "CG": { es:"Congo", en:"Congo", pt:"Congo", fr:"Congo", de:"Kongo", it:"Congo" },
  "CD": { es:"R.D. Congo", en:"DR Congo", pt:"R.D. Congo", fr:"R.D. Congo", de:"DR Kongo", it:"R.D. Congo" },
  "GA": { es:"Gabón", en:"Gabon", pt:"Gabão", fr:"Gabon", de:"Gabun", it:"Gabon" },
  "CM": { es:"Camerún", en:"Cameroon", pt:"Camarões", fr:"Cameroun", de:"Kamerun", it:"Camerun" },
  "CF": { es:"Rep. Centroafricana", en:"Central African Rep.", pt:"Rep. Centro-Africana", fr:"Rep. Centrafricaine", de:"Zentralafrikanische Rep.", it:"Rep. Centroafricana" },
  "TD": { es:"Chad", en:"Chad", pt:"Chade", fr:"Tchad", de:"Tschad", it:"Ciad" },
  "NE": { es:"Níger", en:"Niger", pt:"Níger", fr:"Niger", de:"Niger", it:"Niger" },
  "ML": { es:"Mali", en:"Mali", pt:"Mali", fr:"Mali", de:"Mali", it:"Mali" },
  "BF": { es:"Burkina Faso", en:"Burkina Faso", pt:"Burkina Faso", fr:"Burkina Faso", de:"Burkina Faso", it:"Burkina Faso" },
  "SN": { es:"Senegal", en:"Senegal", pt:"Senegal", fr:"Sénégal", de:"Senegal", it:"Senegal" },
  "GM": { es:"Gambia", en:"Gambia", pt:"Gâmbia", fr:"Gambie", de:"Gambia", it:"Gambia" },
  "GN": { es:"Guinea", en:"Guinea", pt:"Guiné", fr:"Guinée", de:"Guinea", it:"Guinea" },
  "SL": { es:"Sierra Leona", en:"Sierra Leone", pt:"Serra Leoa", fr:"Sierra Leone", de:"Sierra Leone", it:"Sierra Leone" },
  "LR": { es:"Liberia", en:"Liberia", pt:"Libéria", fr:"Libéria", de:"Liberia", it:"Liberia" },
  "CI": { es:"Costa de Marfil", en:"Ivory Coast", pt:"Costa do Marfim", fr:"Côte d'Ivoire", de:"Elfenbeinküste", it:"Costa d'Avorio" },
  "GH": { es:"Ghana", en:"Ghana", pt:"Gana", fr:"Ghana", de:"Ghana", it:"Ghana" },
  "TG": { es:"Togo", en:"Togo", pt:"Togo", fr:"Togo", de:"Togo", it:"Togo" },
  "BJ": { es:"Benín", en:"Benin", pt:"Benim", fr:"Bénin", de:"Benin", it:"Benin" },
  "NG": { es:"Nigeria", en:"Nigeria", pt:"Nigéria", fr:"Nigéria", de:"Nigeria", it:"Nigeria" },
  "ST": { es:"Santo Tomé", en:"São Tomé", pt:"São Tomé", fr:"São Tomé", de:"São Tomé", it:"São Tomé" },
  "GQ": { es:"Guinea Ecuatorial", en:"Equatorial Guinea", pt:"Guiné Equatorial", fr:"Guinée équatoriale", de:"Äquatorialguinea", it:"Guinea Equatoriale" },
  "KM": { es:"Comoras", en:"Comoros", pt:"Comores", fr:"Comores", de:"Komoren", it:"Comore" },
  "MG": { es:"Madagascar", en:"Madagascar", pt:"Madagáscar", fr:"Madagascar", de:"Madagaskar", it:"Madagascar" },
  "MU": { es:"Mauricio", en:"Mauritius", pt:"Maurício", fr:"Maurice", de:"Mauritius", it:"Mauritius" },
  "SC": { es:"Seychelles", en:"Seychelles", pt:"Seicheles", fr:"Seychelles", de:"Seychellen", it:"Seychelles" },
  "RE": { es:"Reunión", en:"Réunion", pt:"Reunião", fr:"Réunion", de:"Réunion", it:"Riunione" },
  "YT": { es:"Mayotte", en:"Mayotte", pt:"Maiote", fr:"Mayotte", de:"Mayotte", it:"Mayotte" },
  "SH": { es:"Santa Elena", en:"Saint Helena", pt:"Santa Helena", fr:"Sainte-Hélène", de:"St. Helena", it:"Sant'Elena" },
};

const langs = ["es","en","pt","fr","de","it"];
const dir = path.join(__dirname, "..", "js", "i18n", "locales");

for (const lang of langs) {
  const fn = path.join(dir, lang + ".json");
  const data = JSON.parse(fs.readFileSync(fn, "utf-8"));
  // Añadir sección paises (mapeo país_es -> país_idioma)
  const paises = {};
  for (const [code, names] of Object.entries(PAISES)) {
    paises[names.es] = names[lang];
  }
  data.paises = paises;
  fs.writeFileSync(fn, JSON.stringify(data, null, 2), "utf-8");
  console.log(lang + ": " + Object.keys(paises).length + " países añadidos");
}